### ISSUE TITLE
Segmentation fault: decodeRcBase (Sam.hpp)

### ISSUE THREAD

**Issue by arun-sub** [Illumina/DRAGMAP#4]
I was trying out DRAGMAP to align one of the Illumina Platinum Genome datasets: [fastq1](https://storage.googleapis.com/genomics-public-data/platinum-genomes/fastq/ERR194147_1.fastq.gz), [fastq2](https://storage.googleapis.com/genomics-public-data/platinum-genomes/fastq/ERR194147_2.fastq.gz) and hit a segmentation fault after aligning around ~86 million reads to the [hg38](https://storage.googleapis.com/genomics-public-data/references/hg38/v0/Homo_sapiens_assembly38.fasta) reference genome.

**gdb reports this line:** 
```
generateSequence<dragenos::sequences::Read, dragenos::align::Alignment> (a=..., read=..., os=...) at ./dragmap/src/include/align/Sam.hpp:127
127             os << ReadT::decodeRcBase(*it);
```

**Here is the backtrace:**
```
#0  generateSequence<dragenos::sequences::Read, dragenos::align::Alignment> (a=..., read=..., os=...) at ./dragmap/src/include/align/Sam.hpp:127
#1  dragenos::align::Sam::generateRecord<dragenos::sequences::Read, dragenos::align::Alignment> (this=0x7fffffffb100, os=..., read=..., alignment=..., rgid="1")
    at ./dragmap/src/include/align/Sam.hpp:73
#2  0x000000000043b55c in dragenos::workflow::DualFastq2SamWorkflow::__lambda10::__lambda12::operator() (__closure=__closure@entry=0x7fff8378cf80, r=..., a=...)
    at ./dragmap/src/lib/workflow/DualFastq2SamWorkflow.cpp:379
#3  0x000000000043bda9 in dragenos::workflow::alignment::storePeSupplementary<dragenos::workflow::DualFastq2SamWorkflow::parseDualFastq(std::istream&, std::istream&, std::ostream&, std::ostream&, std::ostream&)::__lambda10::__lambda12>(const dragenos::align::SinglePicker &, const dragenos::sequences::Read &, dragenos::align::Aligner::Alignments &, dragenos::align::Alignment *, const dragenos::align::Alignment &, dragenos::workflow::DualFastq2SamWorkflow::__lambda10::__lambda12, const dragenos::align::InsertSizeParameters &) (singlePicker=..., read=..., alignments=..., primary=0x7ff1f49285e0, mate=...,
    store=..., insertSizeParameters=...) at ./dragmap/src/include/workflow/alignment/AlignmentUtils.hpp:90
#4  0x000000000043e1ae in alignAndStorePair<dragenos::workflow::DualFastq2SamWorkflow::parseDualFastq(std::istream&, std::istream&, std::ostream&, std::ostream&, std::ostream&)::__lambda10::__lambda12> (
    store=..., alignmentPairs=std::vector of length 32, capacity 512 = {...}, pairBuilder=..., singlePicker=..., aligner=..., pair=..., insertSizeParameters=...)
    at ./dragmap/src/include/workflow/alignment/AlignmentUtils.hpp:233
#5  alignDualFastq<dragenos::workflow::DualFastq2SamWorkflow::parseDualFastq(std::istream&, std::istream&, std::ostream&, std::ostream&, std::ostream&)::__lambda10::__lambda12> (this=0x7fffffffc400,
    store=..., pairBuilder=..., singlePicker=..., aligner=..., inputR2=..., inputR1=..., insertSizeParameters=...) at ./dragmap/src/lib/workflow/DualFastq2SamWorkflow.cpp:107
#6  dragenos::workflow::DualFastq2SamWorkflow::__lambda10::operator() (__closure=0x7fffffffb3a0, lock=...) at ./dragmap/src/lib/workflow/DualFastq2SamWorkflow.cpp:396
#7  0x000000000048e5e6 in unsafeExecute (executor=0x7fffffffb1d0, lock=..., this=0x724620 <dragenos::common::CPU_THREADS(unsigned long)::pool>)
    at ./dragmap/src/include/common/Threads.hpp:314
#8  safeExecute (executor=0x7fffffffb1d0, lock=..., this=0x724620 <dragenos::common::CPU_THREADS(unsigned long)::pool>) at /x/arunsub/winter_21/dragmap/src/include/common/Threads.hpp:332
#9  executeAllPending (lock=..., this=0x724620 <dragenos::common::CPU_THREADS(unsigned long)::pool>) at ./dragmap/src/include/common/Threads.hpp:371
#10 dragenos::common::BasicThreadPool<false>::threadFunc (this=0x724620 <dragenos::common::CPU_THREADS(unsigned long)::pool>) at ./dragmap/src/include/common/Threads.hpp:350
#11 0x00007ffff6799070 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007ffff60a1ea5 in start_thread () from /usr/lib64/libpthread.so.0
#13 0x00007ffff58b28dd in clone () from /usr/lib64/libc.so.6
```

**Command line:**
```
./build/release/dragen-os -r ./index -1 ERR194147_1.fastq.gz -2 ERR194147_2.fastq.gz --output-directory ./sam --output-file-prefix ERR194147
```

**System configuration:**
Centos 7.6, gcc 4.8.5, boost 1.53.0, zlib 1.2.11

Thanks for looking into this.

**Comment by rizkg** [comment]
Hi Arun,
Many thanks for the detailed bug report. We are looking into it.

**Comment by rizkg** [comment]
Hi,  
This is now fixed.
There is not a new release yet, you should use the master branch for now.
